# Generated by Django 4.1.6 on 2023-02-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EuroMillion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_tirage', models.DateField()),
                ('boules_gagnantes_en_ordre_croissant', models.CharField(max_length=20)),
                ('etoiles_gagnantes_en_ordre_croissant', models.CharField(max_length=10)),
                ('boule_1', models.IntegerField()),
                ('boule_2', models.IntegerField()),
                ('boule_3', models.IntegerField()),
                ('boule_4', models.IntegerField()),
                ('boule_5', models.IntegerField()),
                ('numero_chance_1', models.IntegerField()),
                ('numero_chance_2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_tirage', models.DateField()),
                ('combinaison_gagnante_en_ordre_croissant', models.CharField(max_length=20)),
                ('boule_1', models.IntegerField()),
                ('boule_2', models.IntegerField()),
                ('boule_3', models.IntegerField()),
                ('boule_4', models.IntegerField()),
                ('boule_5', models.IntegerField()),
                ('numero_chance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OccurrencesNumerosChanceEuroMillion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chance', models.IntegerField()),
                ('occurrences', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OccurrencesNumerosChanceLoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chance', models.IntegerField()),
                ('occurrences', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OccurrencesNumerosEuroMillion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('occurrences', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OccurrencesNumerosLoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('occurrences', models.IntegerField()),
            ],
        ),
    ]
